import type { AffinityConfig } from './types';

export const AFFINITIES: AffinityConfig[] = [
  {
    id: 'code',
    label: 'Développement',
    emoji: '💻',
    color: '#6366f1',
    gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    description: 'Programmation, architecture, IA, open source',
  },
  {
    id: 'musculation',
    label: 'Musculation',
    emoji: '💪',
    color: '#f97316',
    gradient: 'linear-gradient(135deg, #f97316, #ef4444)',
    description: 'Entraînement, nutrition, récupération, performance',
  },
  {
    id: 'psychologie',
    label: 'Psychologie',
    emoji: '🧠',
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #06b6d4, #3b82f6)',
    description: 'Cognition, comportement, bien-être, thérapies',
  },
  {
    id: 'finances',
    label: 'Finances',
    emoji: '📈',
    color: '#10b981',
    gradient: 'linear-gradient(135deg, #10b981, #14b8a6)',
    description: 'Investissement, épargne, crypto, immobilier',
  },
];

export const TOPICS: Record<string, string[]> = {
  code: [
    'Les fondamentaux des systèmes distribués et pourquoi ils changent tout',
    'Comment les LLMs transforment le métier de développeur en 2025',
    'Architecture hexagonale : principes et application concrète',
    'Le garbage collector expliqué : mémoire, performance et optimisation',
    'Rust vs Go : quel langage pour les systèmes haute performance ?',
    'Les design patterns qui survivent au temps en ingénierie logicielle',
    'DevOps et culture d\'ingénierie : ce que les meilleures équipes font différemment',
    'Tests automatisés : stratégies pour une codebase sans régression',
    'Comprendre les bases de données vectorielles et leur rôle dans l\'IA',
    'Open source : comment contribuer et en tirer un avantage de carrière',
  ],
  musculation: [
    'Hypertrophie musculaire : les mécanismes biologiques complets',
    'Nutrition périodisée : manger pour la performance et la récupération',
    'Programmation de l\'entraînement : volume, intensité et fréquence',
    'Les adaptations neuromusculaires et comment les exploiter',
    'Sommeil et croissance musculaire : la science de la récupération',
    'Supplémentation intelligente : ce qui fonctionne vraiment selon la science',
    'Technique et prévention des blessures : les erreurs les plus communes',
    'Périodisation ondulante : le secret des athlètes de haut niveau',
    'Métabolisme et composition corporelle : comment optimiser les deux',
    'La psychologie de la progression : mindset, discipline et consistance',
  ],
  psychologie: [
    'Les biais cognitifs qui sabotent vos décisions quotidiennes',
    'Thérapie cognitivo-comportementale : principes et auto-application',
    'Neuroplasticité : comment le cerveau se reconfigure à tout âge',
    'Intelligence émotionnelle : un guide complet de développement',
    'L\'effet Dunning-Kruger et les illusions de compétence',
    'Psychologie des habitudes : boucle, routine et récompense',
    'Trauma et résilience : les mécanismes de la reconstruction',
    'La solitude choisie vs l\'isolement subi : impact psychologique',
    'Motivation intrinsèque vs extrinsèque : ce que la science dit',
    'Psychologie sociale : conformisme, persuasion et influence',
  ],
  finances: [
    'L\'investissement passif vs actif : que dit vraiment la recherche ?',
    'Comprendre les marchés financiers et leurs cycles historiques',
    'Immobilier locatif : stratégies, risques et rendements réels',
    'Fiscalité de l\'investissement : optimiser légalement en France',
    'Les cryptomonnaies dans une allocation d\'actifs diversifiée',
    'Épargne et effet boule de neige : la puissance des intérêts composés',
    'Analyse fondamentale d\'une entreprise cotée en bourse',
    'Gestion du risque : diversification, corrélation et couverture',
    'Psychologie de l\'investisseur : éviter les pièges émotionnels',
    'Indépendance financière : méthodes et calculs pour y arriver',
  ],
};
